### ISSUE TITLE
Thumbnail bug: 'ListingItemWidget' object has no attribute 'screen'

### ISSUE THREAD

**Issue by mradamcox** [north-road/soar_qgis_plugin#13]
I'm using v1.0.1 of the plugin. When I try to execute a search in the Soar plugin I see the listed results, but no thumbnails appear and I get the following error:

```
An error has occurred while executing Python code: 

AttributeError: 'ListingDetailsWidget' object has no attribute 'screen' 
Traceback (most recent call last):
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/soar/gui/browse_widget.py", line 197, in _on_listing_clicked
    self.listing_details_pane = ListingDetailsWidget(listing)
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/soar/gui/listing_details_widget.py", line 116, in __init__
    download_thumbnail(listing.preview_url, self)
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/soar/gui/thumbnail_manager.py", line 79, in download_thumbnail
    THUMBNAIL_MANAGER_INSTANCE.download(url, widget)
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/soar/gui/thumbnail_manager.py", line 44, in download
    widget.set_thumbnail(self.cache[url])
  File "/home/adam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/soar/gui/listing_details_widget.py", line 124, in set_thumbnail
    dpi_ratio = self.screen().devicePixelRatio()
AttributeError: 'ListingDetailsWidget' object has no attribute 'screen'


Python version: 3.8.10 (default, May 26 2023, 14:05:08) [GCC 9.4.0] 
QGIS version: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdad 

Python Path:
/usr/share/qgis/python
/home/adam/.local/share/QGIS/QGIS3/profiles/default/python
/home/adam/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/adam/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/adam/.local/share/QGIS/QGIS3/profiles/default/python
/home/adam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_stac/lib
/home/adam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
```

FWIW I commented out the line 124 and set `dpi_ratio` to a constant, but then got a similar error from elsewhere:

```
File "/home/adam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/soar/gui/listing_items.py", line 208, in process_thumbnail
              scale_factor = self.screen().devicePixelRatio()
             AttributeError: 'ListingItemWidget' object has no attribute 'screen'
````

Here's my QGIS install info:

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdad
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
Compiled against PROJ | 6.3.1.%3.%4 | Running against PROJ | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.10.2-CAPI-1.16.0
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.6 LTS

**Comment by nyalldawson** [comment]
Fixed in version 1.0.2 -- it'll hit the plugin repository shortly. You should be able to update in ~30 mins.
